# Generated by Django 3.0.7 on 2020-06-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('link', models.CharField(max_length=200, verbose_name='Link')),
                ('price', models.FloatField(verbose_name='Price')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('data', models.TextField(verbose_name='Data')),
                ('time', models.CharField(blank=True, max_length=200, verbose_name='Time')),
                ('Host', models.CharField(max_length=200, verbose_name='Host')),
            ],
        ),
    ]
