# Generated by Django 3.0.7 on 2020-06-18 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_file', models.ImageField(upload_to='', verbose_name='photo')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.HouseModel')),
            ],
        ),
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_participation', models.CharField(default='', max_length=20)),
                ('official_builder', models.CharField(default='', max_length=20)),
                ('name_of_build', models.CharField(default='', max_length=20)),
                ('decoration', models.CharField(default='', max_length=20)),
                ('floor', models.IntegerField(default=0)),
                ('floor_count', models.IntegerField(default=0)),
                ('house_type', models.CharField(default='', max_length=20)),
                ('num_of_rooms', models.IntegerField(default=0)),
                ('total_area', models.CharField(default='', max_length=20)),
                ('living_area', models.CharField(default='', max_length=20)),
                ('kitchen_area', models.CharField(default='', max_length=20)),
                ('deadline', models.CharField(default='', max_length=20)),
                ('phone', models.IntegerField(default=0)),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.HouseModel')),
            ],
        ),
    ]
