# Generated by Django 3.0.7 on 2020-06-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200622_1139'),
        ('apis', '0003_auto_20200619_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housemodel',
            name='house_info',
        ),
        migrations.RemoveField(
            model_name='image',
            name='house',
        ),
        migrations.DeleteModel(
            name='HouseInfo',
        ),
        migrations.DeleteModel(
            name='HouseModel',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
