# Generated by Django 3.0.7 on 2020-06-22 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.IntegerField(default=0, verbose_name='house_id')),
                ('type_of_participation', models.CharField(default='', max_length=20)),
                ('official_builder', models.CharField(default='', max_length=20)),
                ('name_of_build', models.CharField(default='', max_length=20)),
                ('decoration', models.CharField(default='', max_length=20)),
                ('floor', models.IntegerField(default=0)),
                ('floor_count', models.IntegerField(default=0)),
                ('house_type', models.CharField(default='', max_length=20)),
                ('num_of_rooms', models.CharField(default='', max_length=20)),
                ('total_area', models.CharField(default='', max_length=20)),
                ('living_area', models.CharField(default='', max_length=20)),
                ('kitchen_area', models.CharField(default='', max_length=20)),
                ('deadline', models.CharField(default='', max_length=20)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HouseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.IntegerField(default=0, verbose_name='house_id')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('link', models.CharField(max_length=200, verbose_name='Link')),
                ('price', models.FloatField(verbose_name='Price')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('data', models.TextField(verbose_name='Data')),
                ('time', models.CharField(blank=True, max_length=200, verbose_name='Time')),
                ('Host', models.CharField(max_length=200, verbose_name='Host')),
                ('house_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.HouseInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_file', models.ImageField(upload_to='', verbose_name='photo')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.HouseModel')),
            ],
        ),
    ]
