# Generated by Django 3.0.7 on 2020-06-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='photo_file',
        ),
        migrations.AddField(
            model_name='housemodel',
            name='title_image',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Title Image'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_link',
            field=models.CharField(default='', max_length=1000, verbose_name='photo'),
            preserve_default=False,
        ),
    ]
