# Generated by Django 3.0.7 on 2020-06-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200625_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='price',
            field=models.CharField(max_length=200, verbose_name='Price'),
        ),
    ]
