# Generated by Django 3.0.7 on 2020-06-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200625_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
    ]
