# Generated by Django 3.0.7 on 2020-06-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200626_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='kitchen_area',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='living_area',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='total_area',
            field=models.FloatField(default=0),
        ),
    ]
