# Generated by Django 3.0.7 on 2020-06-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200627_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
