# Generated by Django 3.0.7 on 2020-06-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_housemodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='data',
            field=models.TextField(blank=True, null=True, verbose_name='Data'),
        ),
    ]
