# Generated by Django 3.0.7 on 2020-07-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200701_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='city',
            field=models.CharField(blank=True, choices=[(1, 'Тюмень')], max_length=20, null=True),
        ),
    ]
