# Generated by Django 3.0.7 on 2020-07-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200630_1200'),
        ('base', '0007_housemodel_city'),
    ]

    operations = [
    ]
