# Generated by Django 3.0.7 on 2020-07-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_merge_20200714_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='x_cord',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='y_cord',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='city',
            field=models.CharField(blank=True, choices=[(0, 'Тюмень')], max_length=20, null=True),
        ),
    ]
