# Generated by Django 3.0.7 on 2020-08-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20200801_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='ready_to_go',
            field=models.BooleanField(default=True, verbose_name='ready_to_go'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='link',
            field=models.URLField(verbose_name='Link'),
        ),
    ]
