# Generated by Django 3.0.7 on 2020-07-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_housemodel_parsing_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housemodel',
            name='parsing_time',
        ),
    ]
