# Generated by Django 3.0.7 on 2020-07-18 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_housemodel_parsing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='parsing_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
