# Generated by Django 3.0.7 on 2020-07-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20200718_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='parsing_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation_time'),
        ),
    ]
