# Generated by Django 3.0.7 on 2020-08-06 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20200801_1845'),
        ('base', '0014_auto_20200718_1020'),
    ]

    operations = [
    ]
