# Generated by Django 3.0.7 on 2020-08-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_merge_20200806_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseinfo',
            name='data',
            field=models.TextField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='link',
            field=models.URLField(verbose_name='Link'),
        ),
    ]
