# Generated by Django 3.0.7 on 2020-08-06 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20200806_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='house_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.HouseInfo'),
        ),
        migrations.AlterField(
            model_name='image',
            name='house',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.HouseModel'),
        ),
    ]
