# Generated by Django 3.0.7 on 2020-08-06 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20200806_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseinfo',
            name='data',
        ),
        migrations.RemoveField(
            model_name='image',
            name='house_info',
        ),
        migrations.AlterField(
            model_name='image',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.HouseModel'),
        ),
    ]
