# Generated by Django 3.0.7 on 2020-08-07 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20200806_2306'),
        ('base', '0010_auto_20200806_2320'),
    ]

    operations = [
    ]
