# Generated by Django 3.0.7 on 2020-08-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20200825_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientViewSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.CharField(max_length=200, unique=True)),
                ('set_link', models.URLField(max_length=500, unique=True)),
                ('house_set', models.ManyToManyField(to='base.HouseModel')),
            ],
        ),
    ]
