# Generated by Django 3.0.7 on 2020-06-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_phoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='validate',
            field=models.BooleanField(default=False),
        ),
    ]
