# Generated by Django 3.0.7 on 2020-06-19 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_phoneotp_validate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='subscribe',
            new_name='is_subscribe',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscribe_start_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscribe_trial',
        ),
    ]
