# Generated by Django 3.0.7 on 2020-06-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('users', '0006_auto_20200619_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fav_list',
            field=models.ManyToManyField(related_name='fav_list', to='base.HouseModel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ignore_list',
            field=models.ManyToManyField(related_name='ignore_list', to='base.HouseModel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='watched_list',
            field=models.ManyToManyField(related_name='watched_list', to='base.HouseModel'),
        ),
    ]
