# Generated by Django 3.0.7 on 2020-07-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200701_0045'),
        ('users', '0010_auto_20200629_1850'),
    ]

    operations = [
    ]
