# Generated by Django 3.0.7 on 2020-06-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200629_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
