# Generated by Django 3.0.7 on 2020-06-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200629_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='my_referrals',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent_referral',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referral_code',
        ),
    ]
