# Generated by Django 3.0.7 on 2020-06-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200629_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='my_referrals',
        ),
    ]
