# Generated by Django 3.0.7 on 2020-07-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200701_0045'),
        ('users', '0019_user_is_partner'),
    ]

    operations = [
    ]
