# Generated by Django 3.0.7 on 2020-08-13 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_merge_20200714_1633'),
        ('users', '0011_merge_20200718_1455'),
    ]

    operations = [
    ]
