# Generated by Django 3.0.7 on 2020-08-13 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_merge_20200813_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='all_discount_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
